# Generated by Django 5.2 on 2025-05-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
