# Generated by Django 5.2 on 2025-05-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('user', 'User'), ('admin', 'Admin')], default='admin', max_length=20),
        ),
    ]
