# Generated by Django 5.2 on 2025-05-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_updated_date_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
    ]
