# Generated by Django 5.2 on 2025-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='vehicle_type',
            field=models.CharField(choices=[('two-wheeler', 'Two Wheeler'), ('four-wheeler', 'Four Wheeler')], default='two-wheeler', max_length=20),
        ),
    ]
