# Generated by Django 5.2 on 2025-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='product',
            name='vehicle_type',
            field=models.CharField(choices=[('two-wheeler', 'Two Wheeler'), ('four-wheeler', 'Four Wheeler')], default='two-wheeler', max_length=20),
        ),
    ]
