# Generated by Django 5.2 on 2025-05-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_category_vehicle_type_product_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vehicle_type',
            field=models.CharField(choices=[('two wheeler', 'Two Wheeler'), ('four wheeler', 'Four Wheeler')], default='Two Wheeler', max_length=20),
        ),
    ]
